"""Pydantic models representing commands issued by the AI Creator."""

from __future__ import annotations

import json
from typing import Any, Literal, Union

from pydantic import BaseModel, Field


class SpawnPrimitive(BaseModel):
    """Command to spawn a 3D wireframe geometric primitive."""

    action: Literal["spawn"]
    type: Literal["cube", "sphere", "cylinder", "cone", "torus", "line"]
    position: tuple[float, float, float]
    scale: tuple[float, float, float] = (1.0, 1.0, 1.0)
    rotation: tuple[float, float, float] = (0.0, 0.0, 0.0)
    color: tuple[int, int, int] = (0, 255, 65)


class SpawnCreature(BaseModel):
    """Command to spawn an autonomous procedural creature."""

    action: Literal["spawn_creature"]
    kind: Literal["human", "animal"]
    species: str
    position: tuple[float, float, float]
    name: str
    personality: str = ""
    traits: dict[str, float] = Field(default_factory=dict)


class Modify(BaseModel):
    """Command to modify properties of an existing entity."""

    action: Literal["modify"]
    target: int
    property: Literal["color", "scale", "position", "rotation"]
    value: list[float]


class Delete(BaseModel):
    """Command to remove an entity from the world."""

    action: Literal["delete"]
    target: int


class Idle(BaseModel):
    """No-op command when AI Creator observes without modifications."""

    action: Literal["idle"]


Command = Union[SpawnPrimitive, SpawnCreature, Modify, Delete, Idle]


def parse_command(data: dict[str, Any]) -> Command:
    """Validate and instantiate a single Command based on action discriminator."""
    action = data.get("action")
    match action:
        case "spawn":
            return SpawnPrimitive.model_validate(data)
        case "spawn_creature":
            return SpawnCreature.model_validate(data)
        case "modify":
            return Modify.model_validate(data)
        case "delete":
            return Delete.model_validate(data)
        case "idle":
            return Idle.model_validate(data)
        case _:
            raise ValueError(f"Unknown command action: {action!r}")


def parse_commands_json(text: str) -> list[Command]:
    """Parse JSON array of commands generated by the LLM."""
    clean = text.strip()
    # Strip optional markdown code fences
    if clean.startswith("```"):
        lines = clean.splitlines()
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        clean = "\n".join(lines).strip()

    data = json.loads(clean)
    if isinstance(data, dict):
        data = [data]
    if not isinstance(data, list):
        raise ValueError(f"Expected JSON list of commands, got {type(data)}")

    commands: list[Command] = []
    for item in data:
        if isinstance(item, dict):
            try:
                cmd = parse_command(item)
                commands.append(cmd)
            except Exception:
                continue
    return commands
